group: deprecated-2017Q4

language: python

sudo: required

services:
  - docker

python:
  - "2.7"
  - "3.5"

env:
  - TEST="flake8"

before_install:
  - if [ $TEST == "flake8" ]; then sudo apt-get update -qq ; fi
  - if [ $TEST == "flake8" ]; then sudo apt-get install -qq python-pip; fi
  - if [ $TEST == "flake8" ]; then sudo pip install flake8; fi

script:
  - if [ $TEST == "flake8" ]; then ci/flake8.sh; fi
